name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy to deploy branch
        run: |
          git checkout -b deploy --quiet 
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . 
          git commit -m "Build and deploy"
          git push origin deploy
